-- AlterTable
ALTER TABLE `weekly_prize` ADD COLUMN `claimed` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `dateClaimed` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `delivered` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `sent` BOOLEAN NOT NULL DEFAULT false;
